import {readFileSync,writeFileSync,existsSync,mkdirSync,copyFileSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
const here=dirname(fileURLToPath(import.meta.url)),target=process.argv[2];
if(!target)throw Error('Kullanım: node apply-v200.mjs /tam/V197/proje/yolu');
const root=resolve(target),indexPath=resolve(root,'index.html'),assetPath=resolve(root,'assets/claims-v182.js');
if(!existsSync(resolve(root,'api/claims.js')))throw Error('Güncel sunucu api/claims.js eksik. Eski API ile canlıya yayınlamayın.');
let html=readFileSync(indexPath,'utf8');
const before="function openSettings(pane=\"settingsGeneral\"){\n if(getComputedStyle(settingsModal).display===\"none\")window.__activity187?.closeDeletePanel?.();\n settingsModal.style.display=\"grid\";\n document.querySelectorAll(\".settingsTab\").forEach(b=>b.classList.toggle(\"active\",b.dataset.pane===pane));\n document.querySelectorAll(\".settings-pane\").forEach(p=>p.classList.toggle(\"active\",p.id===pane));\n refreshSettings();\n}\nfunction closeSettings(){window.__claims190?.closeEditor?.();window.__activity187?.closeDeletePanel?.();settingsModal.style.display=\"none\"}";
const after="function openSettings(pane=\"settingsGeneral\"){\n const modal=document.getElementById(\"settingsModal\");if(!modal)return;\n window.__claims190?.closeEditor?.(false);\n if(getComputedStyle(modal).display===\"none\")window.__activity187?.closeDeletePanel?.();\n modal.hidden=false;modal.style.visibility=\"\";modal.style.display=\"grid\";\n const box=modal.querySelector(\":scope > .modal\");\n if(box){box.hidden=false;box.style.visibility=\"\";box.style.display=\"\";}\n modal.querySelectorAll(\".settingsTab\").forEach(b=>b.classList.toggle(\"active\",b.dataset.pane===pane));\n modal.querySelectorAll(\".settings-pane\").forEach(p=>p.classList.toggle(\"active\",p.id===pane));\n refreshSettings();\n}\nfunction closeSettings(){\n window.__claims190?.closeEditor?.(false);window.__activity187?.closeDeletePanel?.();\n const modal=document.getElementById(\"settingsModal\");if(modal)modal.style.display=\"none\";\n}";
if(html.includes(before))html=html.replace(before,after);
else if(!html.includes(after))throw Error('Ayarlar kodu beklenen V197 kaynağıyla eşleşmiyor. Hiçbir dosya değiştirilmedi.');
if(!/\/assets\/claims-v182\.js\?v=\d+/.test(html))throw Error('Hakediş script etiketi bulunamadı. Hiçbir dosya değiştirilmedi.');
html=html.replace(/\/assets\/claims-v182\.js\?v=\d+/g,'/assets/claims-v182.js?v=200');
const source=readFileSync(resolve(here,'assets/claims-v182.js'),'utf8');
new Function(source);
const backup=resolve(root,'backup-before-v200-'+Date.now());mkdirSync(backup);
copyFileSync(indexPath,resolve(backup,'index.html'));if(existsSync(assetPath))copyFileSync(assetPath,resolve(backup,'claims-v182.js'));
mkdirSync(dirname(assetPath),{recursive:true});writeFileSync(assetPath,source);writeFileSync(indexPath,html);
console.log('Ön yüz güncellendi. Canlı yayın yapılmadı. Yedek: '+backup);
